package org.jboss.tools.vwatch.service;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;

import org.apache.log4j.Logger;
import org.jboss.tools.vwatch.model.Bundle;
import org.jboss.tools.vwatch.model.Installation;
import org.jboss.tools.vwatch.model.Issue;

/**
 * Service providing final report generating from given installations
 * 
 * @author jpeterka
 * 
 */
public class ReportService {

	Logger log = Logger.getLogger(ReportService.class);

	/**
	 * Generats report
	 * 
	 * @param installations
	 *            given list of installations
	 * @param filter
	 *            filter definition
	 */
	public void generateReport(List<Installation> installations, String filter) {

		File file = new File("output.html");

		try {
			PrintWriter pw = new PrintWriter(file);
			BufferedWriter bw = new BufferedWriter(pw);
			String style = readFile("vwstyle.css");
			bw.append("<html><head><title>JBDS Version Watch</title><style type=\"text/css\">"
					+ style + "</style></head>");
			bw.append("<body><h2>JBDS Version Watch</h2>");

			bw.append("<h2>Feature list</h2>");
			generateTable(bw, installations, true, filter);
			bw.append("</br><h2>Plugin list</h2>");
			generateTable(bw, installations, false, filter);

			bw.append("<p>Generated by VersionWatch 0.2 in " + " "
					+ StopWatch.stop() + " ms</p>");
			bw.append("<p><div class=\"footspace\"></div><p></body></html><p>");
			bw.flush();

			printErrorLogFooter();

		} catch (Exception e) {
			log.error("IO error" + e.getMessage());
			e.printStackTrace();
			return;
		}

		log.info("Report generated file:///" + file.getAbsolutePath());
	}

	private String readFile(String file) throws IOException {
		BufferedReader reader = new BufferedReader(new FileReader(file));
		String line = null;
		StringBuilder stringBuilder = new StringBuilder();
		String ls = System.getProperty("line.separator");

		while ((line = reader.readLine()) != null) {
			stringBuilder.append(line);
			stringBuilder.append(ls);
		}

		reader.close();
		return stringBuilder.toString();
	}

	private void generateTable(BufferedWriter bw,
			List<Installation> installations, boolean feature, String filter)
			throws IOException {

		BundleService bs = new BundleService();

		SortedSet<String> featureSet = new TreeSet<String>();

		for (Installation i : installations) {
			for (Bundle b : i.getBundles(feature)) {
				if (filter == "" || b.getName().contains(filter))
					/*
					if (featureSet.contains(b.getName())) {
						Issue i = new Issue();
						i.setSeverity(2);
						i.setMessage("Multiple bundle versions");
						b.getIssues().add(i);
					}
					*/
					featureSet.add(b.getName());
			}
		}

		bw.append("<table width=\"100%\" max-width=\"1024px\">");

		// first row

		String bundles = "Plugin";
		if (feature) {
			bundles = "Feature";
		}
		if (filter != "")
			bundles += " (filter=*" + filter + "*)";

		printErrorLogHeader(bundles + "s");

		bw.append("<tr class=\"header\"><td><b>" + bundles + "</b></td>");

		for (Installation i : installations) {
			bw.append("<td><b>" + i.getRootFolderName() + "</b></td>");
		}
		bw.append("</tr>\n");

		// next rows
		for (String s : featureSet) {
			bw.append("<tr><td id=\"" + bundles + "_" + s + "\"><a href=\"#"
					+ bundles + "_" + s + "\">" + s + "</a></td>");

			for (Installation i : installations) {
				Bundle bundleFromList = bs.getBundleFromList(
						i.getBundles(feature), s);					
				
				System.out.println(s);
				
				String tooltip = " title=\"" + i.getRootFolderName() + "&#10;";
				if (bundleFromList != null) {
					tooltip += bundleFromList.getFullName() + "&#10;";
					String c = "";

					int max = bundleFromList.getMaxSeverity();
					if (max == 0)
						c = " class=\"normal\" ";
					else if (max == 1)
						c = " class=\"causion\" ";
					else if (max == 2)
						c = " class=\"warning\" ";
					else if (max == 3)
						c = " class=\"error\" ";

					if (bundleFromList.getIssues().size() > 0) {
						tooltip += bundleFromList.getErrorsAndWarnings();
						tooltip += "\" ";
					} else {
						tooltip += "Nothing suspicious";
						tooltip += "\" ";
						c = " class=\"normal\" ";
					}

					printErrorLogInformation(i, bundleFromList);

					bw.append("<td" + c + " " + tooltip + ">"
							+ bundleFromList.getVersions().toString() + "</td>");
				} else {
					bw.append("<td "
							+ tooltip
							+ "Bundle not available in this version\" class=\"none\">N/A</td>");
				}
			}

			bw.append("</tr>\n");
		}

		bw.append("</table>");

	}

	private void printErrorLogHeader(String text) {
		log.info("----------------------------------------------------------------------------------------------------");
		log.info("Found errors in " + text);
		log.info("----------------------------------------------------------------------------------------------------");
	}

	private void printErrorLogInformation(Installation i, Bundle bundle) {
		for (Issue issue : bundle.getIssues()) {
			if (issue.getSeverity() > 2)
				log.error(bundle.getName() + "," + bundle.getVersion()
						+ " from " + i.getRootFolderName() + " "
						+ issue.getMessage());
		}
	}

	private void printErrorLogFooter() {
		log.info("----------------------------------------------------------------------------------------------------");
	}

}
